import type { Metadata } from "next";

import "./globals.css";
import { Toaster } from "react-hot-toast";
import Navbar from "./components/Navber";



export const metadata: Metadata = {
  title: "devthrought",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"  >
      <body>
        <main className=" bg-[#f0f5fa] ">
          <Navbar/>
          {children}
          <Toaster />
          </main>
      </body>
    </html>
  );
}
